package com.tw;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    private List<Student> students;
    private List<Integer> totalGrades;

    public Library() {
        students =new ArrayList<>();
        totalGrades =new ArrayList<>();
    }

    public void showMainMenu() {
            System.out.print("1.添加学生\n2.生成成绩单\n3.退出\n请输入你的选择（1~3）：\n");
        }

    public boolean isNumber(String num){
        Pattern pattern = Pattern.compile("[0-9]*");
        Matcher isnum = pattern.matcher(num);
        return isnum.matches();
    }
    public boolean isAddStudentInputRight(String input) {
        String[] inputs = input.split("，");
        ArrayList<String> coursename = new ArrayList<String>(){{
            add("数学");
            add("语文");
            add("英语");
            add("编程");
        }};

        if (inputs.length != 6) {
            return false;
        }
        if (!isNumber(inputs[1])) {
            return  false;
        }
        for (int i = 2; i < inputs.length; i++) {
            String[] course = inputs[i].split("：");
            if (course.length != 2) {
                return false;
            }
            if(!coursename.contains(course[0])){
                return false;
            }
            if(!isNumber(course[1])){
                return false;
            }
        }
        return true;
    }
    public void addStudent(String input) {

         if(isAddStudentInputRight(input)){
            Student student=new Student(input);
            students.add(student);
            totalGrades.add(student.getTotalGrade());
            System.out.print("学生"+ student.getName()+"的成绩被添加\n");
            showMainMenu();
        }else {
            System.out.print("请按正确的格式输入（格式：姓名, 学号, 学科: 成绩, ...）：\n"); }
    }

    public double getAverageScore() {
        double averageScore=0.0;
        for(int totalScore: totalGrades)
            averageScore+=totalScore;
        return averageScore/ totalGrades.size();
    }

    public double getMedianScore() {
        Collections.sort(totalGrades);
        if(totalGrades.size()%2==1){
            return totalGrades.get(totalGrades.size()/2);
        }
        else {
            return ((double) totalGrades.get(totalGrades.size()/2)+(double) totalGrades.get(totalGrades.size()/2-1))/2;
        }
    }


    public void showReport(String input) {
        if(input.matches("[，,0-9]*")){
            System.out.print("成绩单\n姓名|数学|语文|英语|编程|平均分|总分\n========================\n");
            String[] strs=input.split(",");
            for (int i = 0; i <strs.length ; i++) {
                for(Student student: students){
                    if (student.getId().equals(strs[i])) {
                        System.out.print(student.getDetailedInfo());
                        break;
                    }
                }
            }
            System.out.print("========================\n全班总分平均数："+getAverageScore()+"\n全班总分中位数："+getMedianScore()+"\n");
            showMainMenu();
        }else {
            System.out.print("请按正确的格式输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：\n");
        }
    }

}
